wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.10.4
    start_time: 1659309204
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 80
      3:
      - 7
      - 13
      - 23
      4: 3.10.4
      5: 0.12.21
      8:
      - 3
      - 5
base_num_filters:
  desc: null
  value: 64
bn_momentum:
  desc: null
  value: 0.1
drop_rate:
  desc: null
  value: 0.4
